/* import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>{children}</body>
    </html>
  );
}
 */
'use client'; // Required to use the usePathname hook.

import React, { useEffect } from 'react';
import { usePathname } from 'next/navigation';
import Breadcrumbs from '@/components/Breadcrumbs'; // Assuming Next.js alias '@/' for 'src/'
import { capitalize } from '@/lib/utils/formatting';
import './globals.css'; // Renamed from app.css for Next.js convention

/*
  Next.js Metadata Note:
  Ideally, metadata is handled in Server Components. For example:

  import type { Metadata } from 'next';
  export const metadata: Metadata = {
    title: {
      default: 'OMS',
      template: 'OMS | %s',
    },
    description: 'OMS App',
  };

  Since this layout needs to be a client component to read the pathname for the
  breadcrumbs, we can't export `metadata`. The `useEffect` below is a direct
  translation of the Svelte component's logic, but for better SEO, you would
  typically use `generateMetadata` in child layouts or pages.
*/

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();

  // Derive title and breadcrumb paths from the current URL
  const pathSegments = pathname.split('/').filter(Boolean);
  const title = pathSegments[pathSegments.length - 1] || 'Home';

  useEffect(() => {
    document.title = `OMS | ${capitalize(title)}`;
  }, [title]);

  return (
    <html lang="en">
      <body>
        <div className="relative flex flex-col min-h-screen bg-gray-200/18 text-gray-900">
          <header className="px-4 py-1 flex justify-end bg-gray-900/20">
            <nav className="flex items-center justify-between w-full mx-auto h-[60px]">
              <Breadcrumbs paths={pathSegments} />
            </nav>
          </header>
          <main className="flex flex-col items-center justify-center p-4 w-full h-full">
            <div className="w-full mx-auto max-w-6xl flex flex-col items-start gap-4 py-6">
              {children}
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
